name: righteouscomplex
favicon: null
layout_spectrum: 0.0016104048117995262
typography_spectrum: 0.497549909632653
title: The Official City Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.609808677341789
  lightness: 0.055173847591504455
  saturation: 0.11826124880462885
  rhythmicContrast: 0.900245800614357
purpose: []
