name: righteouscomplex
favicon: null
layout_spectrum: 0.23867
typography_spectrum: 0.34396
title: The Official City Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#ebeae5'
    - '#473d3c'
    - '#a1a6aa'
    - '#7a7a44'
  brandStrength: 0.5
  lightness: 0.055173847591504455
  saturation: 0.11826124880462885
  rhythmicContrast: 0
purpose: []
